<div>To be notified, enter a real telegram id and/or an email.</div>
<div><a href="https://web.telegram.org/k/#@username_to_id_bot" target="_blank">Find out your telegram id</a></div>
<h3>Add USER</h3>
<section>
    <?php if($createResults): ?>
        <section class="result"><?=$createResults?></section>
    <?php endif; ?>
    <?php if($createErrors): ?>
        <section class="error">
            <?php foreach($createErrors as $error): ?>
                <div><?=$error?></div>
            <?php endforeach; ?>
        </section>
    <?php endif; ?>
    <form action="/user/create" method="post">
        <label for="name"></label>
        <input maxlength="100" type="text" name="name" id="name" placeholder="Name" value="<?=$createData?->name?>" required/>
        <label for="email"></label>
        <input maxlength="200" type="text" name="email" id="email" placeholder="Email" value="<?=$createData?->email?>" />
        <label for="telegram"></label>
        <input maxlength="200" type="text" name="telegram" id="telegram" placeholder="Telegram" value="<?=$createData?->telegram?>" />
        <button type="submit">Add</button>
    </form>
</section>
