<h1>HOME PAGE</h1>
<div>The telegram bot will notify "your user" with a message and the uploaded pdf file.</div>
<br>
<div>To be notified:</div>
<br>
<div>- add a user from the "User" page</div>
<small>Enter a real telegram id and/or an email.</small>
<br>
<small><a href="https://web.telegram.org/k/#@username_to_id_bot" target="_blank">Find out your telegram id</a></small>
<br>
<br>
<div>- upload a pdf file from the "File" page</div>
<br>
<div>Then go to "Notify" page in the top menu, choose a user and press "Notify".</div>